
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.util.ArrayList;
import java.util.Iterator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author student
 */
public class Draw_Geometry extends javax.swing.JFrame {

    /**
     * Creates new form Draw_Geometry
     */
    public Draw_Geometry() {
        initComponents();
    }
    private Graphics2D g;
    private int x1, y1, x2, y2;
    Line2D LineBuffer;
    ArrayList <Line2D> linelist=new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lineradio = new javax.swing.JRadioButton();
        circleradio = new javax.swing.JRadioButton();
        rectangularradio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );

        buttonGroup1.add(lineradio);
        lineradio.setText("Line");

        buttonGroup1.add(circleradio);
        circleradio.setText("Circle");
        circleradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleradioActionPerformed(evt);
            }
        });

        buttonGroup1.add(rectangularradio);
        rectangularradio.setText("Rectangular");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lineradio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(circleradio)
                .addGap(79, 79, 79)
                .addComponent(rectangularradio)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lineradio)
                    .addComponent(circleradio)
                    .addComponent(rectangularradio))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void circleradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_circleradioActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel1.getGraphics();

        if (lineradio.isSelected()) {
            //g.drawLine(0, 0, 100, 100);

            g.draw(new Line2D.Double((double) 50.5, (double) 50.5, (double) 150.5, (double) 150.5));
        }
        if (circleradio.isSelected()) {
            g.drawOval(50, 50, 150, 150);
            g.setColor(Color.red);
            g.fillOval(50, 50, 150, 150);
        }
        if (rectangularradio.isSelected()) {
            //g.drawLine(0, 0, 100, 100);

            //g.draw(new Line2D.Double((double)50.5,(double)50.5,(double)150.5,(double)150.5));
            g.drawRect(10, 10, 250, 250);
            //g.drawRect(x1, y1, x2, y2);
            g.setColor(Color.green);
            g.fillRect(10, 10, 250, 250);
        }

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        g = (Graphics2D) jPanel1.getGraphics();

        x1 = evt.getX();
        y1 = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:
        //g=(Graphics2D) jPanel1.getGraphics();

        /*if (lineradio.isSelected()) {
            jPanel1.update(g);
            x2 = evt.getX();
            y2 = evt.getY();
            LineBuffer=new Line2D.Double((double) x1, (double) y1, (double) x2, (double) y2);
            linelist.add(LineBuffer);
            draw();
            //g.draw(new Line2D.Double((double) x1, (double) y1, (double) x2, (double) y2));
        }*/
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        if (lineradio.isSelected()) {
            jPanel1.update(g);
            x2 = evt.getX();
            y2 = evt.getY();
            //g.draw(new Line2D.Double((double) x1, (double) y1, (double) x2, (double) y2));
        }
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public void draw()
    {
        Iterator itr=linelist.iterator();
        Line2D L1=(Line2D)itr.next();
        for(int i=0;i<linelist.size();i++)
        {
            g.draw(linelist.get(i));
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Draw_Geometry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Draw_Geometry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Draw_Geometry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Draw_Geometry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Draw_Geometry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton circleradio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton lineradio;
    private javax.swing.JRadioButton rectangularradio;
    // End of variables declaration//GEN-END:variables
}
